apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: beer-app-frontend
    workspace: ./frontend/
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/beer-app-frontend/*.yaml
