# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beer_likes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='beer_likes.proto',
  package='beerlikes',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x62\x65\x65r_likes.proto\x12\tbeerlikes\"#\n\x07RefType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"G\n\x04Like\x12$\n\x08ref_type\x18\x01 \x01(\x0b\x32\x12.beerlikes.RefType\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05liked\x18\x03 \x01(\x08\"\x17\n\tLikeQuery\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\nLikesQuery\x12$\n\x08ref_type\x18\x01 \x01(\x0b\x32\x12.beerlikes.RefType\"S\n\x0cLikesSummary\x12\x1e\n\x05likes\x18\x01 \x03(\x0b\x32\x0f.beerlikes.Like\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x14\n\x0c\x65lapsed_time\x18\x03 \x01(\x04\x32\xbd\x01\n\tBeerLikes\x12\x32\n\x07GetLike\x12\x14.beerlikes.LikeQuery\x1a\x0f.beerlikes.Like\"\x00\x12\x37\n\tListLikes\x12\x15.beerlikes.LikesQuery\x1a\x0f.beerlikes.Like\"\x00\x30\x01\x12\x43\n\x0fGetLikesSummary\x12\x15.beerlikes.LikesQuery\x1a\x17.beerlikes.LikesSummary\"\x00\x42/\n\x1bphriscage.beerapp.beerlikesB\x0e\x42\x65\x65rLikesProtoP\x01\x62\x06proto3')
)




_REFTYPE = _descriptor.Descriptor(
  name='RefType',
  full_name='beerlikes.RefType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='beerlikes.RefType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='beerlikes.RefType.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=66,
)


_LIKE = _descriptor.Descriptor(
  name='Like',
  full_name='beerlikes.Like',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_type', full_name='beerlikes.Like.ref_type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='beerlikes.Like.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='liked', full_name='beerlikes.Like.liked', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=139,
)


_LIKEQUERY = _descriptor.Descriptor(
  name='LikeQuery',
  full_name='beerlikes.LikeQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='beerlikes.LikeQuery.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=164,
)


_LIKESQUERY = _descriptor.Descriptor(
  name='LikesQuery',
  full_name='beerlikes.LikesQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_type', full_name='beerlikes.LikesQuery.ref_type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=216,
)


_LIKESSUMMARY = _descriptor.Descriptor(
  name='LikesSummary',
  full_name='beerlikes.LikesSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='likes', full_name='beerlikes.LikesSummary.likes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='beerlikes.LikesSummary.total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elapsed_time', full_name='beerlikes.LikesSummary.elapsed_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=301,
)

_LIKE.fields_by_name['ref_type'].message_type = _REFTYPE
_LIKESQUERY.fields_by_name['ref_type'].message_type = _REFTYPE
_LIKESSUMMARY.fields_by_name['likes'].message_type = _LIKE
DESCRIPTOR.message_types_by_name['RefType'] = _REFTYPE
DESCRIPTOR.message_types_by_name['Like'] = _LIKE
DESCRIPTOR.message_types_by_name['LikeQuery'] = _LIKEQUERY
DESCRIPTOR.message_types_by_name['LikesQuery'] = _LIKESQUERY
DESCRIPTOR.message_types_by_name['LikesSummary'] = _LIKESSUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RefType = _reflection.GeneratedProtocolMessageType('RefType', (_message.Message,), dict(
  DESCRIPTOR = _REFTYPE,
  __module__ = 'beer_likes_pb2'
  # @@protoc_insertion_point(class_scope:beerlikes.RefType)
  ))
_sym_db.RegisterMessage(RefType)

Like = _reflection.GeneratedProtocolMessageType('Like', (_message.Message,), dict(
  DESCRIPTOR = _LIKE,
  __module__ = 'beer_likes_pb2'
  # @@protoc_insertion_point(class_scope:beerlikes.Like)
  ))
_sym_db.RegisterMessage(Like)

LikeQuery = _reflection.GeneratedProtocolMessageType('LikeQuery', (_message.Message,), dict(
  DESCRIPTOR = _LIKEQUERY,
  __module__ = 'beer_likes_pb2'
  # @@protoc_insertion_point(class_scope:beerlikes.LikeQuery)
  ))
_sym_db.RegisterMessage(LikeQuery)

LikesQuery = _reflection.GeneratedProtocolMessageType('LikesQuery', (_message.Message,), dict(
  DESCRIPTOR = _LIKESQUERY,
  __module__ = 'beer_likes_pb2'
  # @@protoc_insertion_point(class_scope:beerlikes.LikesQuery)
  ))
_sym_db.RegisterMessage(LikesQuery)

LikesSummary = _reflection.GeneratedProtocolMessageType('LikesSummary', (_message.Message,), dict(
  DESCRIPTOR = _LIKESSUMMARY,
  __module__ = 'beer_likes_pb2'
  # @@protoc_insertion_point(class_scope:beerlikes.LikesSummary)
  ))
_sym_db.RegisterMessage(LikesSummary)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033phriscage.beerapp.beerlikesB\016BeerLikesProtoP\001'))

_BEERLIKES = _descriptor.ServiceDescriptor(
  name='BeerLikes',
  full_name='beerlikes.BeerLikes',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=304,
  serialized_end=493,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLike',
    full_name='beerlikes.BeerLikes.GetLike',
    index=0,
    containing_service=None,
    input_type=_LIKEQUERY,
    output_type=_LIKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListLikes',
    full_name='beerlikes.BeerLikes.ListLikes',
    index=1,
    containing_service=None,
    input_type=_LIKESQUERY,
    output_type=_LIKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLikesSummary',
    full_name='beerlikes.BeerLikes.GetLikesSummary',
    index=2,
    containing_service=None,
    input_type=_LIKESQUERY,
    output_type=_LIKESSUMMARY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BEERLIKES)

DESCRIPTOR.services_by_name['BeerLikes'] = _BEERLIKES

# @@protoc_insertion_point(module_scope)
