# Creates an Authentication policy and binds it to service.
# The example forces requests to the "helloworld" service to have a valid JWT.
# Configure issuer, jwks_uri, and services as appropriate.
---
# Define an Istio Auth Policy
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: default
  namespace: default
spec:
  peers:
  - mtls:   # uncomment if you're using mTLS between services (eg. istio-demo-auth.yaml)
  origins:
  - jwt:
      issuer: urn://chrispage-eval.apigee.net ## apigee-istio token inspect fails
      jwks_uri: https://chrispage-eval-test.apigee.net/v3/oauth/certs
  principalBinding: USE_ORIGIN
