---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beer-api-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beer-api
        version: v1
    spec:
      containers:
        - name: beer-api
          image: gcr.io/chrispage-dev/beer-api:2.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
