---
apiVersion: v1
kind: Service
metadata:
  name: beer-api-v2
  labels:
    app: beer-api
spec:
  type: ClusterIP
  ports:
    - port: 5000
      name: http
  selector:
    app: beer-api
    version: v2
