---
apiVersion: v1
kind: Service
metadata:
  name: reviews-api-lb
  labels:
    app: reviews-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 8081
  selector:
    app: reviews-api
