---
apiVersion: v1
kind: Service
metadata:
  name: beer-app-frontend
  labels:
    app: beer-app-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    app: beer-app-frontend
    version: v1
