---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beer-app-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beer-app-frontend
        version: v1
    spec:
      containers:
        - name: beer-app-frontend
          image: gcr.io/chrispage-dev/beer-app-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
