---
apiVersion: v1
kind: Service
metadata:
  name: beer-app-frontend-lb
  labels:
    app: beer-app-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 80
  selector:
    app: beer-app-frontend
    version: v1
